version: '3'
services:
  redis:
    image: 'redis:latest'
  postgres:
    images: 'postgres:latest'
  nginx:
    depends_on:
      - api
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      -"3050:80"
    restart: always
  api:
    depends_on:
      - postgres
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /api/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app/
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app/
    
